### ISSUE TITLE
Чтение настроек из файла

### ISSUE THREAD

**Issue by d-hurricane** [oscript-library/configor#24]
Установлена библиотека версии 0.6.3
Пытаюсь воспроизвести пример чтения настроек из файла, взятый из readme. В результате коллекция параметров пустая.
Случайно нашел решение проблемы: добавил инструкцию автонастройки с пустым аргументом:
```bsl
МенеджерПараметров = Новый МенеджерПараметров();
МенеджерПараметров.УстановитьФайлПараметров("D:\git\other\p.json");
МенеджерПараметров.АвтоНастройка("");
МенеджерПараметров.Прочитать();

ПроксиСервер = МенеджерПараметров.Параметр("Настройки.Глобальные.НастройкиПрокси.Сервер");

Сообщить(ПроксиСервер);
```
Чтение настройки завершается успешно. 
Для чего нужна автонастройка? Она необходима и про нее забыли в документации, или же ее использование здесь является ошибкой?

**Comment by khorevaa** [comment]
Для того чтобы сработало без авто настройки необходимо указать провайдера чтения настроек 
через функцию `ИспользоватьПровайдерJSON()`

Авто настройка ищет подходящий файл в каталоге,
Например, МенеджерПараметров.АвтоНастройка("config", "./config_dir", "yaml json");
`config.json` или `config.yml` в каталоги `./config_dir`

```
// Производит автоматическую настройку провайдеров
//
// Параметры:
//   НаименованиеФайла - Строка - Наименование файла параметров
//   ВложенныйПодкаталог - Строка - Дополнительный каталог, для стандартных путей
//   ИдентификаторыПровайдеров - Строка - Идентификаторы встроенных параметров, по умолчанию <yaml json>
//

```

**Comment by d-hurricane** [comment]
Точно, спасибо.
